# Housing Market

### Introduction:

This time we will create our own dataset with fictional numbers to describe a house market. As we are going to create random data don't try to reason of the numbers.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Create 3 differents Series, each of length 100, as follows: 
1. The first a random number from 1 to 4 
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000

In [2]:
s1 = pd.Series(np.random.randint(1, 5, size=100))
s2 = pd.Series(np.random.randint(1, 4, size=100))
s3 = pd.Series(np.random.randint(10000, 30001, size=100))

### Step 3. Let's create a DataFrame by joinning the Series by column

In [3]:
df = pd.concat([s1, s2, s3], axis=1)
df

    0  1      2
0   4  1  18930
1   1  3  17906
2   2  3  25023
3   4  2  28753
4   4  3  28867
.. .. ..    ...
95  1  2  29874
96  4  3  14502
97  3  3  18854
98  4  3  29884
99  2  3  22674

[100 rows x 3 columns]

### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter

In [4]:
df.rename(columns={0: "bedrs", 1: "bathrs", 2: "price_sqr_meter"}, inplace=True)
df

    bedrs  bathrs  price_sqr_meter
0       4       1            18930
1       1       3            17906
2       2       3            25023
3       4       2            28753
4       4       3            28867
..    ...     ...              ...
95      1       2            29874
96      4       3            14502
97      3       3            18854
98      4       3            29884
99      2       3            22674

[100 rows x 3 columns]

### Step 5. Create a one column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

In [5]:
bigcolumn = pd.concat([s1, s2, s3], axis=0)
bigcolumn

0         4
1         1
2         2
3         4
4         4
      ...
95    29874
96    14502
97    18854
98    29884
99    22674
Length: 300, dtype: int32

### Step 6. Oops, it seems it is going only until index 99. Is it true?

In [6]:
len(bigcolumn)

300

### Step 7. Reindex the DataFrame so it goes from 0 to 299

In [7]:
bigcolumn.reset_index(drop=True, inplace=True)